### ISSUE TITLE
音声のみやビデオのみの場合に javascript エラーが発生する

### ISSUE THREAD

**Issue by happy-tanuki** [nttcom/SkyWay-MultiParty#14]
`new MultiParty(option)` のオプションとして、以下の場合にエラーが発生するようです。

音声のみ (`{ video: false, audio: true }`) の場合:

    multiparty.min.js:1 Uncaught TypeError: Failed to execute 'addTrack' on 'MediaStream': parameter 1 is not of type 'MediaStreamTrack'.

ビデオのみ (`{ video: true, audio: false }`) の場合:

    multiparty.min.js:1 Uncaught InvalidStateError: Failed to execute 'createMediaStreamSource' on 'AudioContext': MediaStream has no audio track

どちらも自分自信の mediaStream を初期化する箇所で発生しているようです。
https://github.com/nttcom/SkyWay-MultiParty/blob/92b49aa9e729e437ffb0b794fc97c51914afe05b/lib/MultiParty.js#L154

ご確認のほどよろしくお願いします。

**Comment by yusuke84** [comment]
@happy-tanuki ご指摘ありがとうございます。
該当箇所のエラーを確認したため、改修させて頂きます。
尚、該当の処理箇所は音声ミュートのための処理となり、現在Firefoxでは上手く動作しません。
今回の改修を行った後、後日抜本的な改修をさせて頂く予定です。
