### ISSUE TITLE
roomオプションを指定すると、動作しない？

### ISSUE THREAD

**Issue by kntmrkm** [nttcom/SkyWay-MultiParty#5]
roomオプション無しでは、タブ間でメッセージが表示されますが、
roomオプション指定すると動作しなくなります。

roomの使い方はどこかに詳細書いてありますかね？

**Comment by riosu** [comment]
```
      multiparty = new MultiParty( {
        "key": "****",
        "room": "aaaaa"
      });
```

上記のように、roomオプションを指定して初期化すると利用可能です。

１点、注意しなければならない点がございまして、
現在のMultiPartyライブラリは以前利用したPeerIDがsessionStorageに残っている場合、
ルームIDが変更された場合でも、以前利用したPeerIDを使う仕様となっています。
本ライブラリは、PeerID内にルーム情報を埋め込むことで、ルーム機能を実現しているため、
sessionStorageにデータが投入された後、ルームIDを変更した場合、正常にルーム機能が動作しません。

短期的な解決策として、ChromeDevToolsなどを用いて、sessionStorageからデータを削除するという方法があります。
```
Resourceタブ → 左カラム[Session Storage] → 当該データを右クリックから削除
```

**Comment by riosu** [comment]
またsessionStorageはタブを閉じた場合等に削除されるので、新しいタブで開発をすると問題なく利用できると思われます。

**Comment by yusuke84** [comment]
@kntmrkm こちらのissueは対応済みとなったのでクローズさせて頂きます。
ご申告ありがとうございました！

**Comment by strikerin5vs5** [comment]
こちらのissueについて追加で質問させてください。
同じAPIキー、同じroom名で指定して繋げても、htmlファイルが異なると繋がらないでしょうか？
サーバーやフォルダパス名は同じです。同じフォルダ内に違うhtmlファイル同士でやろうとしています。
そうすると、room_nameは同じだが、room_idがどうしても異なってきます。
強制的にroom_idを同一させる事は可能でしょうか？

**Comment by yusuke84** [comment]
@strikerin5vs5 ご連絡が遅くなり申し訳ありません。
htmlファイルが異なると同じroomにはつながりません。
FAQを作成しましたので、よろしければ御覧ください。
https://support.skyway.io/hc/ja/articles/115003292428
