### ISSUE TITLE
stopScreenShareが正常に動かない

### ISSUE THREAD

**Issue by alanmshelly** [nttcom/SkyWay-MultiParty#8]
https://github.com/nttcom/SkyWay-MultiParty/blob/master/lib/MultiParty.js#L686

stream.stop() がChrome 45からdeprecateされました。

```
stream.getTracks().forEach(
  function(track){
    track.stop();
  }
)
```

**Comment by yusuke84** [comment]
こちらのPullReqにて対応します。
https://github.com/nttcom/SkyWay-MultiParty/pull/10

**Comment by yusuke84** [comment]
対応済みなのでクローズします。
